title: 
icon: 

views:

  - !include /config/lovelace/Tab1a_Home_Kiosk.yaml


decluttering_templates:

  emergency:
    card: 
      type: conditional
      conditions:
        - entity: '[[entity]]'
          state: '[[state]]'
      card:
        type: custom:button-card
        name: '[[name]]'
        deep_press: true
        icon: 'mdi:alert' 
        size: 28px
        aspect_ratio: 7/1
        show_name: true
        show_icon: true
        show_state: false
        show_label: false
        show_last_changed: false
        styles:
          card:
#            - --ha-card-background: '#d40404'
            - --ha-card-background: '#c0392b'
            - animation: blink 2s ease infinite
          name:
            - font-size: 15px
            - font-family: Helvetica
            - color: white
            - justify-self: start
            - padding-left: 18px
            - padding-top: 5px
          img_cell:
            - align-self: start
            - text-align: start
            - margin-left: 21px
          grid: 
            - grid-template-areas: '"i n"'
            - grid-template-columns: 8% 1fr
            - grid-template-rows: 1fr
          icon:
            - color: white
        state:
          - value: "off"

  alert:
    card: 
      type: conditional
      conditions:
        - entity: '[[entity]]'
          state: '[[state]]'
      card:
        type: custom:button-card
        name: '[[name]]'
        deep_press: true
        icon: 'mdi:alert' 
        size: 28px
        aspect_ratio: 7/1
        show_name: true
        show_icon: true
        show_state: false
        show_label: false
        show_last_changed: false
        styles:
          card:
            - --ha-card-background: '#c0392b'
          name:
            - font-size: 15px
            - font-family: Helvetica
            - color: white
            - justify-self: start
            - padding-left: 18px
            - padding-top: 5px
          img_cell:
            - align-self: start
            - text-align: start
            - margin-left: 21px
          grid: 
            - grid-template-areas: '"i n"'
            - grid-template-columns: 8% 1fr
            - grid-template-rows: 1fr
          icon:
            - color: white
#        state:
#          - value: "off"

  warning:
    card: 
      type: conditional
      conditions:
        - entity: '[[entity]]'
          state: '[[state]]'
      card:
        type: custom:button-card
        name: '[[name]]'
        deep_press: true
        icon: 'mdi:alert-circle' 
        size: 28px
        aspect_ratio: 7/1
        show_name: true
        show_icon: true
        show_state: false
        show_label: false
        show_last_changed: false
        styles:
          card:
            - --ha-card-background: '#f9c536'
          name:
            - font-size: 15px
            - font-family: Helvetica
            - color: black
            - justify-self: start
            - padding-left: 18px
            - padding-top: 5px
          img_cell:
            - align-self: start
            - text-align: start
            - margin-left: 21px
          grid: 
            - grid-template-areas: '"i n"'
            - grid-template-columns: 8% 1fr
            - grid-template-rows: 1fr
          icon:
            - color: black
        state:
          - value: "off"

  warning_marquee:
    card: 
      type: conditional
      conditions:
        - entity: '[[entity]]'
          state: '[[state]]'
      card:
        type: custom:button-card
        name: >
          [[[return `<marquee>[[name]]<\marquee>`]]]
        deep_press: true
        icon: 'mdi:alert-circle' 
        size: 28px
        aspect_ratio: 7/1
        show_name: true
        show_icon: true
        show_state: false
        show_label: false
        show_last_changed: false
        styles:
          card:
            - --ha-card-background: '#f9c536'
          name:
            - font-size: 15px
            - font-family: Helvetica
            - color: black
            - justify-self: start
            - padding-left: 18px
            - padding-top: 5px
          img_cell:
            - align-self: start
            - text-align: start
            - margin-left: 21px
          grid: 
            - grid-template-areas: '"i n"'
            - grid-template-columns: 8% 1fr
            - grid-template-rows: 1fr
          icon:
            - color: black
        state:
          - value: "off"

  warning_2line:
    card: 
      type: conditional
      conditions:
        - entity: '[[entity]]'
          state: '[[state]]'
      card:
        type: custom:button-card
        name: >
          [[[return `[[name]]`]]]
        deep_press: true
        icon: 'mdi:alert-circle' 
        size: 28px
        aspect_ratio: 28/5
        show_name: true
        show_icon: true
        show_state: false
        show_label: false
        show_last_changed: false
        styles:
          card:
            - --ha-card-background: '#f9c536'
          name:
            - word-wrap: break-word
            - text-overflow: unset
            - white-space: unset
            - word-break: break-word
            - font-size: 15px
            - font-family: Helvetica
            - color: black
            - justify-self: start
            - padding-left: 18px
            - padding-top: 4px
          img_cell:
            - align-self: start
            - text-align: start
            - margin-left: 21px
          grid: 
            - grid-template-areas: '"i n"'
            - grid-template-columns: 8% 1fr
            - grid-template-rows: 1fr
          icon:
            - color: black
        state:
          - value: "off"

  notice_marquee:
    card: 
      type: conditional
      conditions:
        - entity: '[[entity]]'
          state: '[[state]]'
      card:
        type: custom:button-card
        name: >
          [[[return `<marquee>[[name]]<\marquee>`]]]
        deep_press: true
        icon: 'mdi:information' 
        size: 28px
        aspect_ratio: 7/1
        show_name: true
        show_icon: true
        show_state: false
        show_label: false
        show_last_changed: false
        styles:
          name:
            - font-size: 15px
            - font-family: Helvetica
            - justify-self: start
            - padding-left: 18px
            - padding-top: 5px
          img_cell:
            - align-self: start
            - text-align: start
            - margin-left: 21px
          grid: 
            - grid-template-areas: '"i n"'
            - grid-template-columns: 8% 1fr
            - grid-template-rows: 1fr
        state:
          - value: "off"

  low_battery:
    card: 
      type: conditional
      conditions:
        - entity: '[[entity]]'
          state: '[[state]]'
      card:
        type: custom:button-card
        name: '[[name]]'
        deep_press: true
        icon: 'mdi:battery-30' 
        size: 28px
        aspect_ratio: 7/1
        show_name: true
        show_icon: true
        show_state: false
        show_label: false
        show_last_changed: false
        styles:
          name:
            - font-size: 15px
            - font-family: Helvetica
            - justify-self: start
            - padding-left: 18px
            - padding-top: 5px
          img_cell:
            - align-self: start
            - text-align: start
            - margin-left: 21px
          grid: 
            - grid-template-areas: '"i n"'
            - grid-template-columns: 8% 1fr
            - grid-template-rows: 1fr
        state:
          - value: "off"

  very_low_battery:
    card: 
      type: conditional
      conditions:
        - entity: '[[entity]]'
          state: '[[state]]'
      card:
        type: custom:button-card
        name: '[[name]]'
        deep_press: true
        icon: 'mdi:battery-10' 
        size: 28px
        aspect_ratio: 7/1
        show_name: true
        show_icon: true
        show_state: false
        show_label: false
        show_last_changed: false
        styles:
          card:
            - --ha-card-background: '#f9c536'
          name:
            - font-size: 15px
            - font-family: Helvetica
            - color: black
            - justify-self: start
            - padding-left: 18px
            - padding-top: 5px
          img_cell:
            - align-self: start
            - text-align: start
            - margin-left: 21px
          grid: 
            - grid-template-areas: '"i n"'
            - grid-template-columns: 8% 1fr
            - grid-template-rows: 1fr
          icon:
            - color: black
        state:
          - value: "off"

  very_low_battery_marquee:
    card: 
      type: conditional
      conditions:
        - entity: '[[entity]]'
          state: '[[state]]'
      card:
        type: custom:button-card
        name: >
          [[[return `<marquee>[[name]]<\marquee>`]]]
        deep_press: true
        icon: 'mdi:battery-10' 
        size: 28px
        aspect_ratio: 7/1
        show_name: true
        show_icon: true
        show_state: false
        show_label: false
        show_last_changed: false
        styles:
          card:
            - --ha-card-background: '#f9c536'
          name:
            - font-size: 15px
            - font-family: Helvetica
            - color: black
            - justify-self: start
            - padding-left: 18px
            - padding-top: 5px
          img_cell:
            - align-self: start
            - text-align: start
            - margin-left: 21px
          grid: 
            - grid-template-areas: '"i n"'
            - grid-template-columns: 8% 1fr
            - grid-template-rows: 1fr
          icon:
            - color: black
        state:
          - value: "off"

  open_windows_hot:
    card: 
      type: conditional
      conditions:
        - entity: 'binary_sensor.open_window_making_house_hot'
          state: 'on'
      card:
        type: custom:button-card
        name: >
          [[[return `<marquee> ${states['input_text.windows_making_house_hot'].state} <\marquee>`]]]
        deep_press: true
        icon: 'mdi:fire' 
        size: 28px
        aspect_ratio: 7/1
        show_name: true
        show_icon: true
        show_state: false
        show_label: false
        show_last_changed: false
        styles:
          name:
            - font-size: 15px
            - font-family: Helvetica
            - justify-self: start
            - padding-left: 18px
            - padding-top: 5px
          img_cell:
            - align-self: start
            - text-align: start
            - margin-left: 21px
          grid: 
            - grid-template-areas: '"i n"'
            - grid-template-columns: 8% 1fr
            - grid-template-rows: 1fr
        state:
          - value: "off"

  open_windows_cold:
    card: 
      type: conditional
      conditions:
        - entity: 'binary_sensor.open_window_making_house_cold'
          state: 'on'
      card:
        type: custom:button-card
        name: >
          [[[return `<marquee> ${states['input_text.windows_making_house_cold'].state} <\marquee>`]]]
        deep_press: true
        icon: 'mdi:snowflake' 
        size: 28px
        aspect_ratio: 7/1
        show_name: true
        show_icon: true
        show_state: false
        show_label: false
        show_last_changed: false
        styles:
          name:
            - font-size: 15px
            - font-family: Helvetica
            - justify-self: start
            - padding-left: 18px
            - padding-top: 5px
          img_cell:
            - align-self: start
            - text-align: start
            - margin-left: 21px
          grid: 
            - grid-template-areas: '"i n"'
            - grid-template-columns: 8% 1fr
            - grid-template-rows: 1fr
        state:
          - value: "off"

  open_windows_cold_nomarquee:
    card: 
      type: conditional
      conditions:
        - entity: 'binary_sensor.open_window_making_house_cold'
          state: 'on'
      card:
        type: custom:button-card
        name: >
          [[[return `${states['input_text.windows_making_house_cold'].state}`]]]
        deep_press: true
        icon: 'mdi:snowflake' 
        size: 21px
        aspect_ratio: 2/1
        show_name: true
        show_icon: true
        show_state: false
        show_label: false
        show_last_changed: false
        styles:
          name:
            - word-wrap: break-word
            - text-overflow: unset
            - white-space: unset
            - word-break: break-word
            - font-size: 15px
            - font-family: Helvetica
            - justify-self: start
            - padding-left: 18px
            - padding-top: 4px
            - padding-right: 4px
          img_cell:
            - align-self: start
            - text-align: start
            - margin-left: 22px
          grid: 
            - grid-template-areas: '"i n"'
            - grid-template-columns: 8% 1fr
            - grid-template-rows: 1fr
        state:
          - value: "off"

  open_windows_hot_nomarquee:
    card: 
      type: conditional
      conditions:
        - entity: 'binary_sensor.open_window_making_house_hot'
          state: 'on'
      card:
        type: custom:button-card
        name: >
          [[[return `${states['input_text.windows_making_house_hot'].state}`]]]
        deep_press: true
        icon: 'mdi:snowflake' 
        size: 21px
        aspect_ratio: 2/1
        show_name: true
        show_icon: true
        show_state: false
        show_label: false
        show_last_changed: false
        styles:
          name:
            - word-wrap: break-word
            - text-overflow: unset
            - white-space: unset
            - word-break: break-word
            - font-size: 15px
            - font-family: Helvetica
            - justify-self: start
            - padding-left: 18px
            - padding-top: 4px
            - padding-right: 4px
          img_cell:
            - align-self: start
            - text-align: start
            - margin-left: 22px
          grid: 
            - grid-template-areas: '"i n"'
            - grid-template-columns: 8% 1fr
            - grid-template-rows: 1fr
        state:
          - value: "off"

