
- id: christmas_tree_toggle
  alias: christmas_tree_toggle
  initial_state: 'false'
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.fibaro_button_white
      scene_data: 7680
      scene_id: 1
  action:
    - service: switch.toggle
      data:
        entity_id: switch.miele_dishwasher_switch

- id: christmas_mode_button
  alias: christmas_mode_button
  initial_state: 'false'
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.fibaro_button_white
      scene_data: 7800
      scene_id: 1
  condition:
    condition: template
    value_template: "{{ now().strftime('%F') <= (now().strftime('%Y') | int ) ~ '-12-31' and now().strftime('%F') > (now().strftime('%Y') | int ) ~ '-12-24' }}"
  action:
    - choose:
      - conditions:
        - condition: state
          entity_id: input_boolean.christmas_mode
          state: 'off'
        sequence:
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.itunes_shuffle
          - service: switch.turn_on
            data:
              entity_id: switch.miele_dishwasher_switch
          - service: media_player.play_media
            data:
              entity_id: media_player.chromecast
              media_content_type: cast
              media_content_id: '
                {
                  "app_name": "youtube",
                  "media_id": "8WBThkkpnaA"
                }'
          - event: ALEXA_LAUNCH_ITUNES_PLAYLIST
            event_data_template: 
              alexa_entity: "christmas"
              playlist: "christmas"
          - service: dreamscreen.set_ambient_scene
            data:
              entity_id: dreamscreen.living_room_tv
              scene: 6
          - service: dreamscreen.set_brightness
            data:
              entity_id: dreamscreen.living_room_tv
              brightness: 90
          - service: remote.turn_on
            entity_id: remote.harmony
            data:
               activity: "Chrome Cast"
          - service: remote.send_command
            data:
              entity_id: remote.harmony
              command:
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown   
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown 
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown          
              device: "Sony TV"
              delay_secs: 0.0
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.christmas_mode
      - conditions:
        - condition: state
          entity_id: input_boolean.christmas_mode
          state: 'on'
        sequence:
        - service: media_player.media_pause
          data:
            entity_id: media_player.itunes
        - service: switch.turn_off
          data:
            entity_id: switch.miele_dishwasher_switch
        - service: dreamscreen.set_brightness
          data:
            entity_id: dreamscreen.living_room_tv
            brightness: 42
        - service: dreamscreen.set_mode
          data:
            entity_id: dreamscreen.living_room_tv
            mode: 1
        - service: dreamscreen.set_mode
          data:
            entity_id: dreamscreen.living_room_tv
            mode: 0
        - service: remote.turn_off
          data:
            entity_id: remote.harmony
        - service: media_player.turn_off
          data:
            entity_id: media_player.chromecast
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.christmas_mode

- id: christmas_day_automation
  alias: christmas_day_automation
  initial_state: 'false'
  mode: single
  trigger:
    platform: state
    entity_id: binary_sensor.play_room_zone_3
    to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ now().strftime('%F') < (now().strftime('%Y') | int ) ~ '-12-25' and now().strftime('%F') >= (now().strftime('%Y') | int ) ~ '-12-24' }}"
        - condition: time
          after: '06:00:00'
          before: '11:00:00'
  action:
    - choose:
      - conditions:
        - condition: state
          entity_id: input_boolean.christmas_mode
          state: 'off'
        sequence:
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.itunes_shuffle
          - service: switch.turn_on
            data:
              entity_id: switch.miele_dishwasher_switch
          - service: media_player.play_media
            data:
              entity_id: media_player.chromecast
              media_content_type: cast
              media_content_id: '
                {
                  "app_name": "youtube",
                  "media_id": "8WBThkkpnaA"
                }'
          - event: ALEXA_LAUNCH_ITUNES_PLAYLIST
            event_data_template: 
              alexa_entity: "christmas"
              playlist: "christmas-sorted"
          - service: dreamscreen.set_ambient_scene
            data:
              entity_id: dreamscreen.living_room_tv
              scene: 6
          - service: dreamscreen.set_brightness
            data:
              entity_id: dreamscreen.living_room_tv
              brightness: 90
          - service: remote.turn_on
            entity_id: remote.harmony
            data:
               activity: "Chrome Cast"
          - service: remote.send_command
            data:
              entity_id: remote.harmony
              command:
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown   
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown 
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown
                - VolumeDown          
              device: "Sony TV"
              delay_secs: 0.0
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.christmas_mode
          - delay: 
              hours: 18