
#- id: christmas_tree_toggle
#  alias: christmas_tree_toggle
#  initial_state: 'false'
#  trigger:
#  - platform: event
#    event_type: zwave.scene_activated
#    event_data:
#      entity_id: zwave.fibaro_button_white
#      scene_data: 7680
#      scene_id: 1
#  action:
#    - service: switch.toggle
#      data:
#        entity_id: switch.garbage_disposal

- id: christmas_mode_button
  alias: christmas_mode_button
  initial_state: 'false'
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.fibaro_button_white
      scene_data: 7800
      scene_id: 1
  condition:
    condition: template
    value_template: "{{ now().strftime('%F') <= (now().strftime('%Y') | int ) ~ '-12-31' and now().strftime('%F') > (now().strftime('%Y') | int ) ~ '-12-24' }}"
  action:
    - choose:
      - conditions:
        - condition: state
          entity_id: input_boolean.christmas_mode
          state: 'off'
        sequence:
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.itunes_shuffle
          - service: switch.turn_on
            data:
              entity_id: switch.garbage_disposal
          - service: remote.turn_on
            entity_id: remote.harmony
            data:
              activity: "YouTube"
          - service: media_player.play_media
            data:
              entity_id: media_player.philips936_tv_cast
              media_content_type: cast
              media_content_id: '
                {
                  "app_name": "youtube",
                  "media_id": "DL6wzjjjTB0"
                }'
          - event: ALEXA_LAUNCH_ITUNES_PLAYLIST
            event_data_template: 
              alexa_entity: "christmas"
              playlist: "Christmas-Sorted"
#          - service: dreamscreen.set_ambient_scene
#            data:
#              entity_id: dreamscreen.living_room_tv
#              scene: 6
#          - service: dreamscreen.set_brightness
#            data:
#              entity_id: dreamscreen.living_room_tv
#              brightness: 90
          - delay: "00:00:20"
          - service: remote.send_command
            data:
              delay_secs: 10
              device: Philips TV
              command: Mute
            target:
              entity_id: remote.harmony
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.christmas_mode
      - conditions:
        - condition: state
          entity_id: input_boolean.christmas_mode
          state: 'on'
        sequence:
        - service: media_player.media_pause
          data:
            entity_id: media_player.itunes
        - service: switch.turn_off
          data:
            entity_id: switch.garbage_disposal
#        - service: dreamscreen.set_brightness
#          data:
#            entity_id: dreamscreen.living_room_tv
#            brightness: 42
#        - service: dreamscreen.set_mode
#          data:
#            entity_id: dreamscreen.living_room_tv
#            mode: 1
#        - service: dreamscreen.set_mode
#          data:
#            entity_id: dreamscreen.living_room_tv
#            mode: 0
        - service: remote.turn_off
          data:
            entity_id: remote.harmony
        - service: media_player.turn_off
          data:
            entity_id: media_player.chromecast
        - service: input_boolean.turn_off
          data:
            entity_id: input_boolean.christmas_mode

- id: christmas_day_automation
  alias: christmas_day_automation
  initial_state: 'true'
  mode: single
  trigger:
    platform: state
    entity_id: binary_sensor.play_room_zone_3
    to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: template
          value_template: "{{ now().strftime('%F') < (now().strftime('%Y') | int ) ~ '-12-25' and now().strftime('%F') >= (now().strftime('%Y') | int ) ~ '-12-24' }}"
        - condition: time
          after: '06:00:00'
          before: '11:00:00'
  action:
    - choose:
      - conditions:
        - condition: state
          entity_id: input_boolean.christmas_mode
          state: 'off'
        sequence:
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.itunes_shuffle
          - service: switch.turn_on
            data:
              entity_id: switch.garbage_disposal
          - service: remote.turn_on
            entity_id: remote.harmony
            data:
              activity: "YouTube"
          - service: media_player.play_media
            data:
              entity_id: media_player.philips936_tv_cast
              media_content_type: cast
              media_content_id: '
                {
                  "app_name": "youtube",
                  "media_id": "DL6wzjjjTB0"
                }'
          - event: ALEXA_LAUNCH_ITUNES_PLAYLIST
            event_data_template: 
              alexa_entity: "christmas"
              playlist: "Christmas-Sorted"
          - delay: '00:00:20'
          - service: remote.send_command
            data:
              delay_secs: 10
              device: Philips TV
              command: Mute
            target:
              entity_id: remote.harmony
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.christmas_mode
          - delay: '18:00:00'



- id: christmas_tree_power_cycle
  alias: christmas_tree_power_cycle
  initial_state: 'false'
  trigger:
    platform: time_pattern
    minutes: "/10"
  condition:
    condition: state
    entity_id: switch.garbage_disposal
    state: 'on'  
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.garbage_disposal
    - delay: 
        seconds: 2
    - service: switch.turn_on
      data:
        entity_id: switch.garbage_disposal


- id: christmas_tv_power_on
  alias: christmas_tv_power_on
  initial_state: 'true'
  trigger:
    platform: time
    at: '5:40:00'
  condition:
    - condition: template
      value_template: "{{ now().strftime('%F') < (now().strftime('%Y') | int ) ~ '-12-25' and now().strftime('%F') >= (now().strftime('%Y') | int ) ~ '-12-24' }}"
  action:
    - service: timer.start
      data:
        entity_id: timer.tv_timer 
        duration: '06:00:00'
