#####################################################################
# Emulated Roku Philips TV App Buttons - Home Assistant 1 Port 8060 #
#####################################################################

# Emulated Roku to App Mapping:
# Prime Video and Netflix have dedicated buttons so not needed here
# Home = Home Activity
# Rev = Hulu
# Fwd = YouTube
# Play = GooglePlay Movies
# Select = TV1 RU
# Left = Power Off
# Right = HDMI 4 (Xbox)
# Down = Curiosity Stream
# Up = HBO Max
# Back = PBS 
# InstantReplay = Plex
# Info = PBS Kids
# BackSpace = HDMI 1 (PlayStation)
# Search = HDMI 3 (Nintendo)

# com.apple.atve.androidtv.appletv


- id: philips_launch_home_harmony_activity
  alias: philips_launch_home_harmony_activity
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: Home
  action:
  - service: remote.turn_on
    target:
      entity_id: remote.harmony
    data:
      activity: "Home Screen"
  - service: remote.send_command
    data:
      device: Philips TV
      command: Home
    target:
      entity_id: remote.harmony


- id: philips_launch_hulu
  alias: philips_launch_hulu
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: Rev
  action:
    service: media_player.play_media
    target:
      entity_id: media_player.philips936_tv
    data:
      media_content_id: >-
        com.hulu.livingroomplus.WKFactivity-com.hulu.livingroomplus
      media_content_type: app
#
#- id: philips_launch_prime_video
#  alias: philips_launch_prime_video
#  initial_state: 'true'
#  trigger:
#    platform: event
#    event_type: roku_command
#    event_data:
#      source_name: Home Assistant
#      type: keypress
#      key: Fwd
#  action:
#    service: media_player.play_media
#    target:
#      entity_id: media_player.philips936_tv
#    data:
#      media_content_id: >-
#        com.amazon.ignition.IgnitionActivity-com.amazon.amazonvideo.livingroom
#      media_content_type: app


- id: philips_launch_google_play_movies
  alias: philips_launch_google_play_movies
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: Play
  action:
    service: media_player.play_media
    target:
      entity_id: media_player.philips936_tv
    data:
      media_content_id: >-
        com.google.android.videos.tv.presenter.activity.TvLauncherActivity-com.google.android.videos
      media_content_type: app

- id: philips_launch_tv1_russia
  alias: philips_launch_tv1_russia
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: Select
  action:
    service: media_player.play_media
    target:
      entity_id: media_player.philips936_tv
    data:
      media_content_id: >-
        ru.kino1tv.android.tv.ui.activity.MainActivity-ru.tv1.android.tv
      media_content_type: app




- id: philips_turn_off
  alias: philips_turn_off
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: Left
  action:
    service: remote.send_command
    target:
      entity_id: remote.philips936_tv
    data:
      command: 
        - Standby



#  action:
#    service: media_player.turn_off
#    target:
#      entity_id: media_player.philips936_tv


- id: philips_launch_youtube
  alias: philips_launch_youtube
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: Fwd
  action:
    service: media_player.play_media
    target:
      entity_id: media_player.philips936_tv
    data:
      media_content_id: >-
        com.google.android.apps.youtube.tv.activity.ShellActivity-com.google.android.youtube.tv
      media_content_type: app

- id: philips_launch_curiosity_stream
  alias: philips_launch_curiosity_stream
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: Down
  action:
    service: media_player.play_media
    target:
      entity_id: media_player.philips936_tv
    data:
      media_content_id: >-
        com.curiosity.activities.OnboardingActivity-com.curiosity.curiositystream.androidtv
      media_content_type: app

#- id: philips_launch_hbo_max
#  alias: philips_launch_hbo_max
#  initial_state: 'true'
#  trigger:
#    platform: event
#    event_type: roku_command
#    event_data:
#      source_name: Home Assistant
#      type: keypress
#      key: Up
#  action:
#    service: media_player.play_media
#    target:
#      entity_id: media_player.philips936_tv
#    data:
#      media_content_id: >-
#        com.hbo.go.LaunchActivity-com.hbo.hbonow
#      media_content_type: app


- id: philips_launch_hbo_max
  alias: philips_launch_hbo_max
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: Up
  action:
    - choose:
      - conditions:
        - condition: state
          entity_id: 'media_player.philips936_tv'
          attribute: app_name
          state: 'TV'      
        sequence:
          - service: remote.send_command
            target:
              entity_id: remote.harmony
            data:
              device: "Philips TV"
              command: Home
              num_repeats: 2
              delay_secs: 1
          - service: remote.send_command
            target:
              entity_id: remote.harmony
            data:
              device: "Philips TV"
              command: DirectionRight
              num_repeats: 6
              delay_secs: 1
          - service: remote.send_command
            target:
              entity_id: remote.harmony
            data:
              device: "Philips TV"
              command: OK
      default:
        - service: media_player.play_media
          target:
            entity_id: media_player.philips936_tv
          data:
            media_content_id: >-
              com.hbo.go.LaunchActivity-com.hbo.hbonow
            media_content_type: app



- id: philips_launch_pbs
  alias: philips_launch_pbs
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: Back
  action:
    service: media_player.play_media
    target:
      entity_id: media_player.philips936_tv
    data:
      media_content_id: >-
        com.pbs.video.ui.main.activities.StartupActivity-com.pbs.video
      media_content_type: app

- id: philips_launch_plex
  alias: philips_launch_plex
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: InstantReplay
  action:
    - choose:
      - conditions:
        - condition: state
          entity_id: 'media_player.philips936_tv'
          attribute: app_name
          state: 'TV'      
        sequence:
          - service: remote.send_command
            target:
              entity_id: remote.harmony
            data:
              device: "Philips TV"
              command: Home
              num_repeats: 2
              delay_secs: 1
          - service: remote.send_command
            target:
              entity_id: remote.harmony
            data:
              device: "Philips TV"
              command: DirectionRight
              num_repeats: 3
              delay_secs: 1
          - service: remote.send_command
            target:
              entity_id: remote.harmony
            data:
              device: "Philips TV"
              command: OK
      default:
        - service: media_player.play_media
          target:
            entity_id: media_player.philips936_tv
          data:
            media_content_id: >-
              com.plexapp.plex.activities.SplashActivity-com.plexapp.android
            media_content_type: app
#media_player.philips936_tv
#app_name: TV

- id: philips_launch_pbs_kids
  alias: philips_launch_pbs_kids
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: Info
  action:
    service: media_player.play_media
    target:
      entity_id: media_player.philips936_tv
    data:
      media_content_id: >-
        org.pbskids.video.splash.ui.SplashScreenActivity-org.pbskids.video
      media_content_type: app

- id: philips_launch_hdmi_1_playstation
  alias: philips_launch_hdmi_1_playstation
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: BackSpace
  action:
    service: media_player.select_source
    data:
      source: HDMI 1
    target:
      entity_id: media_player.philips936_tv

- id: philips_launch_hdmi_3_nintendo
  alias: philips_launch_hdmi_3_nintendo
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: Search
  action:
    service: media_player.select_source
    data:
      source: HDMI 3
    target:
      entity_id: media_player.philips936_tv

- id: philips_launch_hdmi_4_xbox
  alias: philips_launch_hdmi_4_xbox
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant
      type: keypress
      key: Right
  action:
    service: media_player.select_source
    data:
      source: HDMI 4
    target:
      entity_id: media_player.philips936_tv



#####################################################################
# Emulated Roku Philips TV App Buttons - Home Assistant 2 Port 8061 #
#####################################################################

# Emulated Roku to App Mapping:
# Prime Video and Netflix have dedicated buttons so not needed here
# Home = Home Activity (Harmony)
# Rev = Power Off (Remote Command)
# Fwd = Adjust (Remote Command)
# Play = Other Media
# Select = 
# Left = TV Guide
# Right = 
# Down = 
# Up = 
# Back = 
# InstantReplay = 
# Info = 
# BackSpace = 
# Search = 



- id: philips_launch_home_harmony_activity
  alias: philips_launch_home_harmony_activity
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant 2
      type: keypress
      key: Home
  action:
  - service: remote.turn_on
    target:
      entity_id: remote.harmony
    data:
      activity: "Home Screen"
  - service: remote.send_command
    data:
      device: Philips TV
      command: Home
    target:
      entity_id: remote.harmony


- id: philips_turn_off_2
  alias: philips_turn_off_2
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant 2
      type: keypress
      key: Left
  action:
    service: remote.send_command
    target:
      entity_id: remote.philips936_tv
    data:
      command: Standby


- id: philips_launch_other_media
  alias: philips_launch_other_media
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant 2
      type: keypress
      key: Play
  action:
    service: media_player.play_media
    target:
      entity_id: media_player.philips936_tv
    data:
      media_content_id: >-
        org.droidtv.contentexplorer.MainActivity-org.droidtv.contentexplorer
      media_content_type: app

- id: philips_launch_tv_guide
  alias: philips_launch_tv_guide
  initial_state: 'true'
  trigger:
    platform: event
    event_type: roku_command
    event_data:
      source_name: Home Assistant 2
      type: keypress
      key: Left
  action:
    service: media_player.play_media
    target:
      entity_id: media_player.philips936_tv
    data:
      media_content_id: >-
        org.droidtv.channels.ChannelsLauncherActivity-org.droidtv.channels
      media_content_type: app
      
      
#####################################################################      


- id: philips_tv_turn_off_remote
  alias: philips_tv_turn_off_remote
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: media_player.philips936_tv
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: remote.harmony
    state: 'on'
  action:
  - service: remote.send_command
    target:
      entity_id: remote.philips936_tv
    data:
      command: PowerOn
  - delay: 1
  - service: remote.turn_off
    target:
      entity_id: remote.harmony

