        
- id: bio_odpad_day_tomorrow_sean
  alias: bio_odpad_day_tomorrow_sean
  initial_state: 'true'
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: 'sensor.bio_odpad_day'
          state: 'Tomorrow'
        - condition: template
          value_template: "{{ not is_state('sensor.sean_location', 'Traveling') }}"
  action:
    service: notify.mobile_app_sean_iphone_14
    data:
      title: "Bio Odpad Tomorrow"
      message: "Bio odpad should be taken out tonight or tomorrow for collection on {% if now().weekday() in (5,)  %}Monday{% elif now().weekday() in (6,)  %}Tuesday{% elif now().weekday() in (0,)  %}Wednesday{% elif now().weekday() in (1,)  %}Thursday{% elif now().weekday() in (2,)  %}Friday{% elif now().weekday() in (3,)  %}Saturday{% elif now().weekday() in (4,)  %}Sunday{% endif %} morning"
      data:
        push:
          thread-id: "info"

- id: bio_odpad_day_tomorrow_alena
  alias: bio_odpad_day_tomorrow_alena
  initial_state: 'true'
  trigger:
    platform: time
    at: '15:00:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: 'sensor.bio_odpad_day'
          state: 'Tomorrow'
  action:
    service: notify.mobile_app_alena_iphone
    data:
      title: "Bio Odpad Tomorrow"
      message: "Bio odpad should be taken out today or tomorrow for collection on {% if now().weekday() in (5,)  %}Monday{% elif now().weekday() in (6,)  %}Tuesday{% elif now().weekday() in (0,)  %}Wednesday{% elif now().weekday() in (1,)  %}Thursday{% elif now().weekday() in (2,)  %}Friday{% elif now().weekday() in (3,)  %}Saturday{% elif now().weekday() in (4,)  %}Sunday{% endif %} morning"
      data:
        push:
          thread-id: "info"

- id: trash_day_tomorrow_sean
  alias: trash_day_tomorrow_sean
  initial_state: 'true'
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: 'sensor.trash_day'
          state: 'Tomorrow'
        - condition: template
          value_template: "{{ not is_state('sensor.sean_location', 'Traveling') }}"
  action:
    service: notify.mobile_app_sean_iphone_14
    data:
      title: "Trash Tomorrow"
      message: "Trash should be taken out tonight or tomorrow for collection on {% if now().weekday() in (5,)  %}Monday{% elif now().weekday() in (6,)  %}Tuesday{% elif now().weekday() in (0,)  %}Wednesday{% elif now().weekday() in (1,)  %}Thursday{% elif now().weekday() in (2,)  %}Friday{% elif now().weekday() in (3,)  %}Saturday{% elif now().weekday() in (4,)  %}Sunday{% endif %} morning"
      data:
        push:
          thread-id: "info"

- id: trash_day_tomorrow_alena
  alias: 'Trash Day'
  initial_state: 'true'
  trigger:
    platform: time
    at: '15:00:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: 'sensor.trash_day'
          state: 'Tomorrow'
  action:
    service: notify.mobile_app_alena_iphone
    data:
      title: "Trash Tomorrow"
      message: "Trash should be taken out today or tomorrow for collection on {% if now().weekday() in (5,)  %}Monday{% elif now().weekday() in (6,)  %}Tuesday{% elif now().weekday() in (0,)  %}Wednesday{% elif now().weekday() in (1,)  %}Thursday{% elif now().weekday() in (2,)  %}Friday{% elif now().weekday() in (3,)  %}Saturday{% elif now().weekday() in (4,)  %}Sunday{% endif %} morning"
      data:
        push:
          thread-id: "info"

- id: bio_odpad_day_today_sean
  alias: bio_odpad_day_today_sean
  initial_state: 'true'
  trigger:
    platform: time
    at: '21:00:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: 'sensor.bio_odpad_day'
          state: 'Today'
        - condition: template
          value_template: "{{ not is_state('sensor.sean_location', 'Traveling') }}"
  action:
    service: notify.mobile_app_sean_iphone_14
    data:
      title: "Bio Odpad Today"
      message: "Bio odpad should be taken out tonight for collection on {% if now().weekday() in (6,)  %}Monday{% elif now().weekday() in (0,)  %}Tuesday{% elif now().weekday() in (1,)  %}Wednesday{% elif now().weekday() in (2,)  %}Thursday{% elif now().weekday() in (3,)  %}Friday{% elif now().weekday() in (4,)  %}Saturday{% elif now().weekday() in (5,)  %}Sunday{% endif %} morning"
      data:
        push:
          thread-id: "info"
        
- id: bio_odpad_day_today_alena
  alias: bio_odpad_day_today_alena
  initial_state: 'true'
  trigger:
    platform: time
    at: '15:00:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: 'sensor.bio_odpad_day'
          state: 'Today'
  action:
    service: notify.mobile_app_alena_iphone
    data:
      title: "Bio Odpad Today"
      message: "Bio odpad should be taken out today for collection on {% if now().weekday() in (6,)  %}Monday{% elif now().weekday() in (0,)  %}Tuesday{% elif now().weekday() in (1,)  %}Wednesday{% elif now().weekday() in (2,)  %}Thursday{% elif now().weekday() in (3,)  %}Friday{% elif now().weekday() in (4,)  %}Saturday{% elif now().weekday() in (5,)  %}Sunday{% endif %} morning"
      data:
        push:
          thread-id: "info"
        

#- id: trash_day_today_sean
#  alias: 'Trash Day'
#  initial_state: 'true'
#  trigger:
#    - platform: time
#      at: '21:00:00'
#    - platform: time
#      at: '22:00:00'
#    - platform: time
#      at: '23:00:00'
#  condition:
#    - condition: and
#      conditions:
#        - condition: state
#          entity_id: 'sensor.trash_day'
#          state: 'Today'
#        - condition: template
#          value_template: "{{ not is_state('sensor.sean_location', 'Traveling') }}"
#  action:
#    service: notify.mobile_app_sean_iphone_14
#    data:
#      title: "Trash Day Today"
#      message: "Trash should be taken out tonight for collection on {% if now().weekday() in (6,)  %}Monday{% elif now().weekday() in (0,)  %}Tuesday{% elif now().weekday() in (1,)  %}Wednesday{% elif now().weekday() in (2,)  %}Thursday{% elif now().weekday() in (3,)  %}Friday{% elif now().weekday() in (4,)  %}Saturday{% elif now().weekday() in (5,)  %}Sunday{% endif %} morning"
#      data:
#        push:
#          thread-id: "info"
        
- id: trash_day_today_alena
  alias: trash_day_today_alena
  initial_state: 'true'
  trigger:
    platform: time
    at: '15:00:00'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: 'sensor.trash_day'
          state: 'Today'
  action:
    service: notify.mobile_app_alena_iphone
    data:
      title: "Trash Day Today"
      message: "Trash should be taken out today for collection on {% if now().weekday() in (6,)  %}Monday{% elif now().weekday() in (0,)  %}Tuesday{% elif now().weekday() in (1,)  %}Wednesday{% elif now().weekday() in (2,)  %}Thursday{% elif now().weekday() in (3,)  %}Friday{% elif now().weekday() in (4,)  %}Saturday{% elif now().weekday() in (5,)  %}Sunday{% endif %} morning"
      data:
        push:
          thread-id: "info"

- alias: 'update_bio_odpad_sensor'
  trigger:
    platform: time
    at: '00:00:01'
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.bio_odpad_day

- alias: 'update_trash_sensor'
  trigger:
    platform: time
    at: '00:00:01'
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.trash_day


- id: turn_on_trash_input_boolean
  alias: "Turn On Trash Input Boolean"
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: sensor.trash_day
    to: 'Tomorrow'
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.trash_needs_taking_out

- id: turn_off_trash_input_boolean
  alias: "Turn Off Trash Input Boolean"
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: sensor.trash_day
    to: 'false'
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.trash_needs_taking_out

- id: notification_turn_off_trash_input_boolean
  alias: notification_turn_off_trash_input_boolean
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: TOOK_TRASH_OUT
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.trash_needs_taking_out


- id: update_trash_display
  alias: update_trash_display
  trigger:
    platform: time_pattern
    minutes: 15
  action:
    service: homeassistant.update_entity
    entity_id: binary_sensor.trash_display


- id: update_trash_emergency_sensor
  alias: update_trash_emergency_sensor
  trigger:
    platform: time_pattern
    minutes: 5
  action:
    service: homeassistant.update_entity
    entity_id: binary_sensor.trash_emergency

- id: coming_home_trash_day_alena
  alias: coming_home_trash_day_alena
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: device_tracker.alenas_iphone
    to: 'home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: 'sensor.trash_day'
      state: 'Today'
    - condition: state
      entity_id: 'input_boolean.trash_needs_taking_out'
      state: 'on'
  action:
    service: notify.mobile_app_alena_iphone
    data:
      title: "Take out that trash!"
      message: "Hello there, today is trash day and now would be a really great time to take out the trash, what do you think? Let's do it, what do you say?!?"
      data:
        push:
          sound:
            name: "News_Flash.caf"
            critical: 1
            volume: 1.0
          thread-id: "location"

- id: coming_home_trash_day_sean
  alias: coming_home_trash_day_sean
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: device_tracker.seans_iphone_14
    to: 'home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: 'sensor.trash_day'
      state: 'Today'
    - condition: state
      entity_id: 'input_boolean.trash_needs_taking_out'
      state: 'on'
  action:
    service: notify.mobile_app_sean_iphone_14
    data:
      title: "Take out that trash!"
      message: "Hello there, now would be a really great time to take out the trash, what do you think? Let's do it, what do you say?!?"
      data:
        push:
          sound:
            name: "News_Flash.caf"
            critical: 1
            volume: 1.0
          thread-id: "location"

- id: coming_home_bio_odpad_day_sean
  alias: coming_home_bio_odpad_day_sean
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: device_tracker.seans_iphone_14
    to: 'home'
  condition:
    condition: state
    entity_id: 'sensor.bio_odpad_day'
    state: 'Today'
  action:
    service: notify.mobile_app_sean_iphone_14
    data:
      title: "Take out that bio odpad!"
      message: "Hello there, now would be a really great time to take out the bio odpad, what do you think? Let's do it, what do you say?!?"
      data:
        push:
          sound:
            name: "News_Flash.caf"
            critical: 1
            volume: 1.0
          thread-id: "location"

- id: coming_home_bio_odpad_day_alena
  alias: coming_home_bio_odpad_day_alena
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: device_tracker.alenas_iphone
    to: 'home'
  condition:
    condition: state
    entity_id: 'sensor.bio_odpad_day'
    state: 'Today'
  action:
    service: notify.mobile_app_alena_iphone
    data:
      title: "Take out that bio odpad!"
      message: "Hello there, now would be a really great time to take out the bio odpad, what do you think? Let's do it, what do you say?!?"
      data:
        push:
          sound:
            name: "News_Flash.caf"
            critical: 1
            volume: 1.0
          thread-id: "location"


- id: opening_garage_trash_day
  alias: opening_garage_trash_day
  initial_state: 'true'
  trigger:
    platform: state
    entity_id: binary_sensor.basement_sliding_door
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: 'sensor.trash_day'
      state: 'Today'
    - condition: state
      entity_id: 'input_boolean.trash_needs_taking_out'
      state: 'on'
    - condition: time
      after: "17:00:00"
      before: "23:59:00"
      action:
  action:
    - delay: 0:05
    - service: script.announce_trash_day_trash_not_out
#    - service: notify.alexa_media_alexa_garage
#      data:
#        message: "Hello there, today is trash day and it looks like the trash hasn't been taken out. Would you mind doing it please?"

